version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./src/static:/static
      - ./src//media:/media
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: django
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn VulgaireDev.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - ./src/static:/src/static
      - ./src/media:/src/media
    expose:
      - "8000"

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
     # - ./db_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: Souirnarlor45
       MYSQL_DATABASE: vulgairedev 
       MYSQL_USER: vulgairedev 
       MYSQL_PASSWORD: Souirnarlor45 
