# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 10:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170429_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 30, 10, 20, 22, 947094, tzinfo=utc), verbose_name='Date de parution'),
        ),
    ]
