# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170430_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 30, 13, 4, 31, 522494, tzinfo=utc), verbose_name='Date de parution'),
        ),
    ]
