# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170430_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 30, 13, 10, 40, 941693, tzinfo=utc), verbose_name='Date de parution'),
        ),
    ]
